const CHANGE_WATCH = "CHANGE_WATCH";
const CHANGE_STAR = "CHANGE_STAR";
const CHANGE_FORK = "CHANGE_FORK"
const ERROR = "ERROR";
const REQUEST = "REQUEST";
const FETCH_DATA = "FETCH_DATA";
const NEXT_PAGE = "NEXT_PAGE";


export {
  CHANGE_STAR,
  CHANGE_WATCH,
  CHANGE_FORK, 
  FETCH_DATA,
  NEXT_PAGE,
  ERROR,
  REQUEST
};
